import type { Metadata } from "next";

import React, { Fragment } from "react";

export const metadata: Metadata = {
    title: "MyCvSUDorm - Listings",
    authors: {
        name: "Waffen Sultan",
        url: "https://github.com/waffenffs"
    },
    description: "Generated by create next app",
}

export default function Layout({ children }: { children: React.ReactNode}) {
    return (
        <Fragment>
            {children}
        </Fragment>
    )
}