import type { Metadata } from "next";
import "./globals.css";

import ThemeProvider from "./components/providers/theme-provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "MyCvSUDorm",
  authors: {
    name: "Waffen Sultan",
    url: "https://github.com/waffenffs"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider 
          attribute="class" 
          defaultTheme="light"
        >
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
